/**:
  ros__parameters:
    robot_description_planning:
      # joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

      # For beginners, we downscale velocity and acceleration limits.
      # You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
      default_velocity_scaling_factor: 0.1
      default_acceleration_scaling_factor: 0.1

      # Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
      # Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
      joint_limits:
        group_1/joint_1:
          has_velocity_limits: true
          max_velocity: 1.832596
          has_acceleration_limits: true
          max_acceleration: 3.0
          has_deceleration_limits: true
          max_deceleration: 3.0
        group_1/joint_2:
          has_velocity_limits: true
          max_velocity: 1.640609
          has_acceleration_limits: true
          max_acceleration: 5.0
          has_deceleration_limits: true
          max_deceleration: 5.0
        group_1/joint_3:
          has_velocity_limits: true
          max_velocity: 1.745329
          has_acceleration_limits: true
          max_acceleration: 5.0
          has_deceleration_limits: true
          max_deceleration: 5.0
        group_1/joint_4:
          has_position_limits: true
          min_position: -0.436332  # -25
          max_position: 0.436332   #  25
          has_velocity_limits: true
          max_velocity: 2.373648
          has_acceleration_limits: true
          max_acceleration: 3.0
          has_deceleration_limits: true
          max_deceleration: 3.0
        group_1/joint_5:
          has_position_limits: true
          min_position: -2.18166  # -125
          max_position: 0.0
          has_velocity_limits: true
          max_velocity: 2.251475
          has_acceleration_limits: true
          max_acceleration: 5.0
          has_deceleration_limits: true
          max_deceleration: 5.0
        group_1/joint_6:
          has_position_limits: true
          min_position: -3.49066  # -200
          max_position: 3.49066   #  200
          has_velocity_limits: true
          max_velocity: 3.595378
          has_acceleration_limits: true
          max_acceleration: 7.0
          has_deceleration_limits: true
          max_deceleration: 7.0
