/**:
  ros__parameters:
    planning_pipelines: ["ompl", "pilz", "stomp"]
    capabilities: []

    ompl:
      planning_plugin: ompl_interface/OMPLPlanner
      request_adapters: >-
        default_planner_request_adapters/AddTimeOptimalParameterization
        default_planner_request_adapters/ResolveConstraintFrames
        default_planner_request_adapters/FixWorkspaceBounds
        default_planner_request_adapters/FixStartStateBounds
        default_planner_request_adapters/FixStartStatePathConstraints
      start_state_max_bounds_error: 0.1

    pilz:
      planning_plugin: pilz_industrial_motion_planner/CommandPlanner
      default_planner_config: PTP

    # Trajectory execution manager parameters
    moveit_manage_controllers: False
    trajectory_execution:
      allowed_execution_duration_scaling: 100.0
      allowed_goal_duration_margin: 0.5
      allowed_start_tolerance: 0.01

    # Planning scene monitor parameters
    publish_planning_scene: true
    publish_geometry_updates: true
    publish_state_updates: true
    publish_transforms_updates: true
