/**:
  ros__parameters:
    pilz:
      planning_plugins: [pilz_industrial_motion_planner/CommandPlanner]
      default_planner_config: PTP
      request_adapters:
        - default_planning_request_adapters/ResolveConstraintFrames
        - default_planning_request_adapters/ValidateWorkspaceBounds
        - default_planning_request_adapters/CheckStartStateBounds
        - default_planning_request_adapters/CheckStartStateCollision
      response_adapters:
        - default_planning_response_adapters/AddTimeOptimalParameterization
        - default_planning_response_adapters/ValidateSolution
        - default_planning_response_adapters/DisplayMotionPath
