/**:
  ros__parameters:
    pilz:
      request_adapters:
        - default_planning_request_adapters/CheckStartStateBounds
        # - default_planner_request_adapters/FixWorkspaceBounds
        # - default_planner_request_adapters/FixStartStateBounds
        # - default_planner_request_adapters/FixStartStatePathConstraints
