/**:
  ros__parameters:
    stomp:
      planning_plugin: stomp_moveit/StompPlanner
      request_adapters:
        - default_planning_request_adapters/CheckStartStateBounds
        # - default_planning_request_adapters/AddTimeOptimalParameterization
        # - default_planning_request_adapters/FixWorkspaceBounds
        # - default_planning_request_adapters/FixStartStateBounds
        # - default_planning_request_adapters/FixStartStateCollision
        # - default_planning_request_adapters/FixStartStatePathConstraints

      stomp_moveit:
        num_timesteps: 60
        num_iterations: 40
        num_iterations_after_valid: 0
        num_rollouts: 30
        max_rollouts: 30
        exponentiated_cost_sensitivity: 0.5
        control_cost_weight: 0.1
        delta_t: 0.1
