controller_names:
  - position_trajectory_controller

position_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
      - group_1/joint_1
      - group_1/joint_2
      - group_1/joint_3
      - group_1/joint_4
      - group_1/joint_5
      - group_1/joint_6
